### PR TITLE
Introduce a CSV import helper

### LINKED ISSUE #14: `.csv` import helper
# Objective #

- Simplify the quick evaluation of the kit.

# Definition of Done #

- There is a direct import function able to take the path to a `.csv` file.

### PR DESCRIPTION
**Pull request by alexisfontaine**
Closes #14.

### CODE REVIEW

**Comment by cloderic** [comment]
Maybe a way to directly handle the records provided as a file path would be nice (additional method or "magic" handling of the `records` parameter)

**Comment by alexisfontaine** [comment]
You mean, from an instance of endpoint (i.e. loading the CSV file and updating the craft ai agent all at once)?

**Comment by cloderic** [comment]
> You mean, from an instance of endpoint (i.e. loading the CSV file and updating the craft ai agent all at once)?

yes

**Comment by alexisfontaine** [comment]
Done!

A path to a CSV file can now be provided directly as the first argument of the methods:
- `endpoint.update()`
- `endpoint.computePredictions()`
- `endpoint.computeAnomalies()`
- `endpoint.computeReport()`

The import process for those methods can be configured the same way as with the main function `EnergyKit.import.csv()`, i.e. through the second argument. The only difference is that the import configuration must be contained inside an `import` property.

> ⚠ The signature of the method `endpoint.computePredictions()` has been changed to include an `options` argument.

**Pull request merged**
